### ISSUE TITLE
📢Alibaba Summer of Code 2020

### ISSUE THREAD

**Issue by carp84** [realtime-storage-engine/flink-spillable-statebackend#1]
Welcome to the open source world! If you haven't planned how to spend this summer, come to the Alibaba Summer of Code and coding with us! 💻

Alibaba Summer of Code is a global program focused on engaging students directly into open source software development. Under the guidance of the mentor in the Alibaba open source project, students experience the software development in the real world.Alibaba Summer of code will begin between May 25th and September 5th. Students can use the summer time to participate in the open source project and work with the core members of the project.

# What you can get
On this exclusive developer journey, you will have the opportunity to:
* Participate in the top projects of the International Open Source Foundation;
* Get a scholarship from Alibaba;
* Obtain an open source contributor certificate;
* Get a fast pass of Alibaba Internship/recruitment;
* Get your code adopted and used by the open source project！

# Our Mentor
* Yu Li (@carp84), Apache HBase PMC member, Apache Flink committer

# Apply Now!
Idea list (feel free to submit new ideas):
* https://github.com/realtime-storage-engine/flink-spillable-statebackend/labels/ASoC2020

You can click on this link to apply directly:
* Chinese: https://developer.aliyun.com/topic/summerofcode2020
* English: https://www.alibabacloud.com/campaign/summerofcode2020

# Timeline⏳

![image](https://user-images.githubusercontent.com/6239804/82560116-6124d600-9ba3-11ea-9cf2-cd9b8decf427.png)

# Contact us!

Email Address: liyu@apache.org

**Comment by aryamanpuri** [comment]
Hi @carp84, I am interested in ASOC 2020?
Can you help me out with a few starting resources or where should I start from?

**Comment by carp84** [comment]
Thanks for the interest @aryamanpuri , you can apply following instructions on https://www.alibabacloud.com/zh/campaign/summerofcode2020

**Comment by aryamanpuri** [comment]
Is there any communication medium for the discussions ?

**Comment by carp84** [comment]
Post all topics here for your convenience:

**Topic-1: Traffic Forecasting for Flink Job**
* Most of flink jobs are streaming jobs, which are long running,  generally, the traffic of job is varying smoothly by time. In order to make sure that a job can catch up with the data  rate, we need to develop a model to support traffic forcasting for flink job, so that we can adjust the configuration of the job dynamically according to the traffic need to process.
* In this topic you need to implement a traffic forcasting model for flink jobs, The model should be able to:
  1. predicate future input rate of a flink job according to history metrics.
  2. be trained online on per job basis since different jobs could have different patterns of traffic.
  3. be refined according the gap between observed rate and predicted rate, since the job will be running in long time, we have the chance to correct the model.
* This is a typical issue of time series forecating, which is already widely applied in many other scenarios, classic algorithms such as ARIMA can can be considered as the options of solution.

**Topic-2: Design and implement the encoder for Hash-based Page**
* State storage is on the critical path of Flink, a stateful computing engine. Basically it's a kv store but with computing-relative requirement, thus an interdisciplinary area.
* Gemini is a KeyValue store we designed for such scenario. To improve lookup performance, Gemini uses hash table to index pages, and key/value pairs in a page are organized in a hash-based format. Approaches to encode keys based-on ssorted index, such as key prefix encoding, may be not applicable to hash-based pages. 
* In this topic you need to design and implement a key encoder for hash-based pages, which aims at reducing the disk space consumption, with low CPU consumption and high lookup throughput.

**Topic-3: Improvement for Flink Spillable Statebackend**
* State storage is on the critical path of Flink, a stateful computing engine. Basically it's a kv store but with computing-relative requirement, thus an interdisciplinary area.
* We have implemented an enhanced heap state backend to support spilling cold data to disk, using mmap for both reading and writing the on-disk parts. However, the IO amplification of mmap writing is big and uncontrollable.
* In this topic you need to design and implement a better solution for the on-disk writing of spillable backend.

Please join our gitter for more discussion: https://gitter.im/asoc2020-flink/community
