### ISSUE TITLE
Improve and better control the spilling IO

### ISSUE THREAD

**Issue by carp84** [realtime-storage-engine/flink-spillable-statebackend#2]
This issue aims at resolving the 1st TODO item listed in the `Future Work` sector of [FLIP-50](https://cwiki.apache.org/confluence/display/FLINK/FLIP-50%3A+Spill-able+Heap+Keyed+State+Backend).

Now we're using mmap for both reading and writing the on-disk parts. However, the IO amplification of mmap writing is big and uncontrollable. We should find a way to resolve the problem, meantime keep the writing performance. There're quite some storage engine using mmap technology that we could use as a reference.

More details please refer to the FLIP document.

**Comment by carp84** [comment]
Please notice that this spill-able backend is already uploaded onto [flink-packages](https://flink-packages.org/packages/spillable-state-backend-for-flink) and will be merged back to Apache Flink through [FLINK-12692](https://issues.apache.org/jira/browse/FLINK-12692)

**Comment by dernDren161** [comment]
Hi @carp84 , i am interested in this and would like to participate. Do we have a dedicated channel for the project?

**Comment by deepanshu1422** [comment]
@carp84, I've worked on the FLIP-50 before and want to contribute to this project, could you please suggest me the starting node?

**Comment by anubhavpulkit** [comment]
Hi, @carp84 I'm Anubhav Singh ASoC'20 Aspirant. I want to work on this issue.
Can I make a communication channel for this project so we talk about the issue?

**Comment by carp84** [comment]
Sorry for the late response folks. Please follow instructions here to apply: https://www.alibabacloud.com/zh/campaign/summerofcode2020

**Comment by deepanshu1422** [comment]
Hi @carp84 ,

Is the selection for this project purely based upon the proposal; or do we need to perform some prerequisite tasks/Pull requests???

Please confirm

**Comment by anubhavpulkit** [comment]
> Hi @carp84 ,
> 
> Is the selection for this project purely based upon the proposal; or do we need to perform some prerequisite tasks/Pull requests???
> 
> Please confirm

Yes, @carp84 I have the same doubt?

**Comment by coolalexzb** [comment]
Hi @carp84 ,

My name is Bo Zheng, a first year master student of computer scinece at Rice University. I am interested in this project. I think the work flow description you provided is clear, and is similar to some parts of the work I did in Database class. Look forward to contributing to this issue!

**Comment by carp84** [comment]
@deepanshu1422 @anubhavsingh16 Yes, unlike GSoC, ASoC don't require any PR involvement before hand, and mainly decide final candidate by quality of the proposals. And thanks for the interest @coolalexzb 

Looking forward to your proposals folks.

**Comment by Ndonteat** [comment]
Hi @carp84,

I'm Ning, interested in joining this project. Do we have a mailing list/ Slack channel/ Wechat group for discussion? Another question is that, how many candidates will you choose to join this Flink project? 

Looking forward to contribute!

**Comment by carp84** [comment]
@NWdawg thanks for the interest. Please join this channel for discussion: https://gitter.im/asoc2020-flink/community
